### PR TITLE
BaSP- MR-207: message when logged

### PR DESCRIPTION
**Pull request by LucianoStradiot**
Updated the message when a user logs in  on the header

### CODE REVIEW

**Review by Tilajc — APPROVED** [review]
Pretty good job!

**Comment by LucianoStradiot** [comment]
[[FEATURE] Change the message on the header when a user is logged](https://trello.com/c/iiUSaIxg/207-feature-change-the-message-on-the-header-when-a-user-is-logged)

**Review by LautaroVercellini — APPROVED** [review]
Good Job Lucho!

**Review by Tilajc — APPROVED** [review]
Pretty good job!

**Pull request merged**
