### PR TITLE
BaSP-MR-227:added contact feature

### PR DESCRIPTION
**Pull request by Eugeniagassman**
i added contact feature

### CODE REVIEW

**Comment by LucianoStradiot** [comment]
[[FEATURE] - Implement Contact form](https://trello.com/c/4NwMjTNY/227-feature-implement-contact-form)

**Comment by LucianoStradiot** [comment]
[[FEATURE] - Implement Contact form](https://trello.com/c/4NwMjTNY/227-feature-implement-contact-form)

**Review by Tilajc — APPROVED** [review]
Pretty good job!

**Review by Flor-Farruggia — APPROVED** [review]
Nice Job! The contact page was really great! <3

**Review by GaloDurante — COMMENTED** [review]
I recommend you reduce the size of the text on the contact and also add a hover effect

**Pull request merged**
