### PR TITLE
BaSP-MR-105: header footer css

### PR DESCRIPTION
**Pull request by GaloDurante**
Implemet new styles for the page based on Figma of the team

### CODE REVIEW

**Review by Tilajc — APPROVED** [review]
Well Done!

**Comment by LucianoStradiot** [comment]
[[FIX] Error on all components when have no data](https://trello.com/c/y1xoDnvq/116-fix-error-on-all-components-when-have-no-data)

**Comment by LucianoStradiot** [comment]
[General Css for the styles on the header and footer.](https://trello.com/c/wx4C6voR/105-general-css-for-the-styles-on-the-header-and-footer)

**Comment by LautaroVercellini** [comment]
The social media icons in the footer are not working.

**Pull request merged**
